name: Check

on:
  push:
    branches:
      - main

jobs:
  check_without_pub_get:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Run pub get
        run: flutter

      - name: Lint Android
        run: |
          cd android
          ./gradlew lint
